### ISSUE TITLE
System.NullReferenceException  at MonoTorrent.Client.Connections.SocketConnection.<ConnectAsync>d__36.MoveNext()

### ISSUE THREAD

**Issue by borrelnoten** [alanmcgovern/monotorrent#371] opened 2020-12-19 20:16 UTC
when waiting for metadata for a torrent:

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=MonoTorrent
  StackTrace:
   at MonoTorrent.Client.Connections.SocketConnection.<ConnectAsync>d__36.MoveNext()
   at System.Runtime.CompilerServices.ReusableTaskAwaiter.GetResult()
   at MonoTorrent.Client.NetworkIO.<ConnectAsync>d__10.MoveNext()
   at System.Runtime.CompilerServices.ReusableTaskAwaiter.GetResult()

  This exception was originally thrown at this call stack:
    MonoTorrent.Client.Connections.SocketConnection.ConnectAsync()
    System.Runtime.CompilerServices.ReusableTaskAwaiter.GetResult()
    MonoTorrent.Client.NetworkIO.ConnectAsync(MonoTorrent.Client.Connections.IConnection)
    System.Runtime.CompilerServices.ReusableTaskAwaiter.GetResult()

**Comment by alanmcgovern** [comment] 2020-12-19 20:21
Which version are you using? It'll make it easier to diagnose :)

**Comment by borrelnoten** [comment] 2020-12-19 20:27
31

**Comment by alanmcgovern** [comment] 2020-12-19 21:07
I believe the issue will fixed with https://github.com/alanmcgovern/monotorrent/commit/51828084315b766118ca77cf705ce370e0242cc9 .

I'm pretty certain this is a harmless NullRef caused by the connection being disposed before it actually connects. This is normal behaviour when swapping between modes internally.

Let me know if it still occurs after this change is released!

**Closed by alanmcgovern** 2020-12-19 21:07 UTC
