### ISSUE TITLE
Remote client is closing the connection

### ISSUE THREAD

**Issue by carlosib** [alanmcgovern/monotorrent#258] opened 2020-03-03 13:06 UTC
I'll have to look into this some more, but according to wireshark the remote client is closing the connection as soon as the HaveNone message, and AllowedFast messages are received.

![image](https://user-images.githubusercontent.com/14793055/75778442-90f7d680-5d36-11ea-9269-79dee71115ec.png)

This doesn't make sense as everything looks correct up until that point. Odd :) If you can - please open a separate github issue for this as it's unrelated to trackers!

**Comment by almcgo-stripe** [comment] 2020-03-03 14:51
@carlosib The best i can offer is that there's a bug in monotorrent 1.0.0 which is triggering here. Do you own the clients in this swarm? If so is it possible to update them to a newer release like 1.0.15 or 1.0.16?

**Comment by alanmcgovern** [comment] 2020-03-03 19:08
@carlosib I looked into this with a recent monotorrent release and uTorrent. Neither client can successfully connect to peers in this swarm.

I suspect there's a bug in the old(ish) release of monotorrent used by clients in this swarm. If you own these clients then perhaps upgrading them to a modern release would resolve the problem.

**Comment by carlosib** [comment] 2020-03-04 18:41
Hello @alanmcgovern I update my client app (1.0.16.0) and I have same issue.

Test, plase, using those files:
[TorrentsFiles.torrent.zip](https://github.com/alanmcgovern/monotorrent/files/4289090/TorrentsFiles.torrent.zip)

If I open any .torrent file using uTorrent the download is very fast. But, using monotorrent, the download is very very slow :( :(

**Comment by alanmcgovern** [comment] 2020-03-05 00:12
I just loaded them all into uTorrent and even it can't download anything. There seems to only be 1 other active peer on those torrents and that peer only has about 1% of the data. There are no seeders available.

If there's a reproducable testcase which can be run locally that is much easier for me to diagnose. For example if you can run uTorrent and MonoTorrent on the same machine, or run monotorrent twice on the same machine, and reproduce the problem I can use the same setup to diagnose the underlying issue.

One thing that is kind of curious is that uTorrent is connecting to the same IP address multiple times. Do you know if multiple MonoTorrent clients are running on the same computer or is there something else weird going on?
![same_ip](https://user-images.githubusercontent.com/264396/75934982-e5ee3680-5e75-11ea-9193-7c4d86eb987a.png)

**Comment by carlosib** [comment] 2020-03-05 22:51
Hello @alanmcgovern !

> One thing that is kind of curious is that uTorrent is connecting to the same IP address multiple times. Do you know if multiple MonoTorrent clients are running on the same computer or is there something else weird going on?
> 

I have some monotorrents clients in my local network.

Please, do download of (video files and torrent files):
https://we.tl/t-T95zzc5Xyz

My new test:

I tested using 2 monotorrents clients using same computers. 1 instance had all files (videos and torrent) and another instance had only torrent file. The secound instance doesn't do download of videos files.

Another test I used two uTorrent. In the 1 instance I have (videos and torrent files) and another I have only torrent files. The secound instance did download of video files.

After this I did more a test: I used 1 instance uTorrent with videos and torrents files and another insntance of monotorrent client using only torrent file. Monotorrent client didn't do download of videos files.

In my last test I used an instance of monotorrent client with videos and torrent files and another instance of utorrent using only torrent files. uTorrent instance didn't do download of videos files.

**Comment by alanmcgovern** [comment] 2020-03-08 20:20
Hi! I've downloaded those files and will do some testing locally. I'll replicate these two scenarios:

```
1 x MonoTorrent (seeder) and 1 x uTorrent (leecher)
1 x MonoTorrent (leecher) and 1 x uTorrent (seeder)
```

I will make sure that in both cases the data transfer occurs and both clients end up as Seeders. If there are any bugs I'll try to fix them!

Thanks for the source files. If there's a torrent-specific issue I'll be able to find it with these!

**Comment by alanmcgovern** [comment] 2020-03-08 23:37
Let's rule out two 'normal' issues first:

1. Scenario: Run MonoTorrent and uTorrent on the same computer with IP address 192.168.0.2. If uTorrent connects to itself then it will close that connection and all connections coming from 192.168.0.2. That means when MonoTorrent tries to connect to uTorrent, uTorrent will immediately close the connection. This will make it look like MonoTorrent and uTorrent are not compatible, but it's actually just uTorrent attempting to not connect to itself. Resetting the ban lists is unlikely to help because uTorrent will re-ban itself too quickly.

2. Scenario: Leave uTorrent running on a computer with IP address 192.168.0.2. Download using MonoTorrent on a computer with ip address 192.168.0.3. When MonoTorrent has downloaded everything, shut it down, delete the downloaded data, then restart it to download the data again. If you do this you might find that uTorrent will refuse to connect to, or accept connections from, MonoTorrent. This is because uTorrent 'knows' that the client at IP address 192.168.0.3 is a seeder and so would be a waste of resources to allow it to connect. uTorrent *can* sometimes ban the IP address to prevent reconnections. To fix this you can restart uTorrent. You may need to reset the ban lists if all else fails ;) You can also try right click -> advanced -> Clear peer lists.

I would recommend opening the 'Logger' tab in uTorrent and enable all the logging. That will tell you when you hit this kind of issue. you can see the 'same id' and 'banned' statements here. This indicates uTorrent connected to itself:
![banned](https://user-images.githubusercontent.com/264396/76173118-5b1e7c00-6194-11ea-9430-4d1bde122877.png).

I also typically run my tests with no WAN connection so I know the only incoming/outgoing connections are from either MonoTorrent or uTorrent. It makes things easier to debug for me.

*So*, my own experimenting showed that uTorrent can download 100% of the data from a MonoTorrent seed, and MonoTorrent can download 100% of the data from a uTorrent seed.

**Comment by carlosib** [comment] 2020-03-08 23:51
Hello!
Please try to use only monotorrent app. Two instances of monotorrents.



Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by alanmcgovern** [comment] 2020-03-09 00:35
I did just merge this change too as it should help connectivity with uTorrent when it randomises the PeerId rather than using the same one it gives the Tracker:

https://github.com/alanmcgovern/monotorrent/commit/2e70bd204eec458f7f922c2b1489640d07bbec55

**Comment by alanmcgovern** [comment] 2020-03-09 00:38
![two_monotorrent](https://user-images.githubusercontent.com/264396/76174265-329b7f80-619e-11ea-8731-af87a40bcf64.png)

I ran a test with 1 x MonoTorrent (seeder) and 1 x MonoTorrent (leecher) as soon as I left my last comment and it worked as expected. I attached a screenshot of the transfer!

**Comment by alanmcgovern** [comment] 2020-03-09 00:39
![finished](https://user-images.githubusercontent.com/264396/76174288-64ace180-619e-11ea-859f-1fd63f930bfb.png)

And this is the finished download. All three torrents completed and are now seeding. The average transfer rate was between 8 and 10 megabytes/second.

**Comment by alanmcgovern** [comment] 2020-03-09 00:58
@carlosib I just uploaded a new release, 1.0.17. I think this may help MonoTorrent -> uTorrent connections when uTorrents 'randomize_peer_id' option is enabled. This could be the issue you were seeing.

**Comment by carlosib** [comment] 2020-03-10 23:14
Hello @alanmcgovern !

Can you, please, do new test using only monotorrent app? Please, don't use uTorrent.

I did test and never had download using release 1.0.17 version.

Please use only this files:

https://we.tl/t-9R7yYehQuV

**Comment by alanmcgovern** [comment] 2020-03-11 00:45
> Can you, please, do new test using only monotorrent app? Please, don't use uTorrent.
> 
> I did test and never had download using release 1.0.17 version.

Do you know if the two clients are even trying to connect to each other? Can you attach an event handler to `Torrent.ConnectionAttemptFailed`, `TorrentManager.PeerConnected` and `TorrentManager.PeerDisconnected` when running your test. If you can log the Uri each time one of these events is raised we should be able to see if the clients are attempting to connect to each other, or if they're just not getting each others IP/port combo.

You can see the logging I do in the sample client here: https://github.com/alanmcgovern/monotorrent/blob/f6557463add1a93983ea581a372f61790870fa12/src/SampleClient/main.cs#L143-L151

I'll re-run a test tomorrow with the new files (I have them downloaded) and I will use the latest monotorrent release.

My two previous comments, the ones with the screenshots of the console application running, were from when I ran two instances of MonoTorrent 1.0.17 on a local network. They connected to each other using LocalPeerDiscovery and succesfully transferred the other files you shared with me.

**Comment by carlosib** [comment] 2020-03-11 10:56
Hello @alanmcgovern !

> My two previous comments, the ones with the screenshots of the console application running, were from when I ran two instances of MonoTorrent 1.0.17 on a local network. They connected to each other using LocalPeerDiscovery and succesfully transferred the other files you shared with me.

When did you do the test I forget my uTorrent app running. When I test using only monotorrent (without any instance of uTorrent running) I don't have download.

But using monotorrent 1.0 works correctly.

**Comment by carlosib** [comment] 2020-03-11 18:14
Hello @alanmcgovern !

I tested using some others files and I have this errors:

> Connection failed: ipv4://192.168.1.182:3031/ - HandshakeFailed - PlainText, RC4Header  - LIKE_SERIES_ROTASDOODIO_210220.mp4 - 
Connection failed: ipv4://192.168.1.182:3031/ - HandshakeFailed - PlainText  - LIKE_SERIES_ROTASDOODIO_210220.mp4 - 
Connection failed: ipv4://192.168.1.182:3031/ - HandshakeFailed - None  - LIKE_SERIES_ROTASDOODIO_210220.mp4 - 
Connection failed: ipv4://187.94.102.162:3031/ - Unreachable - All  - LIKE_SERIES_ROTASDOODIO_210220.mp4 - 
Connection failed: ipv4://201.65.30.104:3031/ - EncryptionNegiotiationFailed - PlainText  - LIKE_SERIES_ROTASDOODIO_210220.mp4 - 
Connection failed: ipv4://201.65.30.104:3031/ - Unreachable - All  - LIKE_SERIES_ROTASDOODIO_210220.mp4 - 
Connection failed: ipv4://201.65.30.104:3031/ - Unreachable - All  - LIKE_SERIES_ROTASDOODIO_210220.mp4 - 
Connection failed: ipv4://187.94.102.162:3031/ - Unreachable - All  - LIKE_SERIES_ROTASDOODIO_210220.mp4 - 
Connection failed: ipv4://187.94.102.162:3031/ - Unreachable - All  - LIKE_SERIES_ROTASDOODIO_210220.mp4 - 
Connection failed: ipv4://187.94.102.162:3031/ - Unreachable - All  - LIKE_SERIES_ROTASDOODIO_210220.mp4 - 
Connection failed: ipv4://187.94.102.162:3031/ - Unreachable - All  - LIKE_SERIES_ROTASDOODIO_210220.mp4 - 
Connection failed: ipv4://187.94.102.162:3031/ - Unreachable - All  - LIKE_SERIES_ROTASDOODIO_210220.mp4 - 
Connection failed: ipv4://187.94.102.162:3031/ - Unreachable - All  - LIKE_SERIES_ROTASDOODIO_210220.mp4 - 

Please, note, if I open this files using uTorrent i can do download using monotorrent and/or using monotorrent 1.0 I can to able do download of all files.

**Comment by alanmcgovern** [comment] 2020-03-11 20:39
This is quite useful information!

These errors mean the issue is not related to the torrent itself. There's a connectivity issue in the network, or perhaps monotorrent is not being configured to listen on the correct port.

Can you also log this information on each client:
```
if (clientEngine.Listener is ISocketListener)
    ((ISocketListener) clientEngine.Listener).EndPoint;
````
I suspect that the socket MonoTorrent is using to listen for incoming connections is not actually set to listen on port 3031, which is what the other MonoTorrent instances are connecting to.

There's a second way to validate this theory. When you use uTorrent can you see if the connections it creates have an `I` in `flags` column, or if every connection *does not* have an `I`. If this letter is there then itmeans the connection was *incoming*. If my theory is correct and monotorrent is listening on the wrong port, then uTorrent will show all the MonoTorrent connections as 'Incoming' because MonoTorrent can connect to it, but it cannot connect to MonoTorrent.

**Comment by alanmcgovern** [comment] 2020-03-11 20:44
Related update: Everything is working as expected on my side. I can definitely run several copies of MonoTorrent and they can all connect to each other.

I looked at some of the related code in release-v1.0.0 and current master, and it looks the same. I can't really explain how changing the version makes a difference. It's quite odd :s

**Comment by alanmcgovern** [comment] 2020-03-11 22:16
There is one thing you can do to help diagnose the issue.

Assuming you are running the client on ` ipv4://201.65.30.104:3031`, you can manually verify that the IP/Port is actually reachable by using [telnet](https://www.technipages.com/windows-10-enable-telnet). for example: `telnet 201.65.30.104 3031` . If it connects you'll get a blank screen. If you keep typing random characters and pressing 'enter' to send the characters you will eventually get a response from the other client. the response will be gibberish because it'll be an encrypted handshake.

This is a screencast: http://recordit.co/YtzAiurqVz. When the screen is blank i'm actually typing lots of characters and hitting enter. You have to send over 68 characters before you'll get the encrypted response.

**Comment by alanmcgovern** [comment] 2020-03-15 17:28
@carlosib  I was just wondering if you had a chance to check the listening port to make sure it matched what was being sent to the tracker, and what other peers were trying to connect to.

Thanks!

**Comment by carlosib** [comment] 2020-03-16 21:45
Hello @alanmcgovern !

Sorry my delay :( :(

I am running my monotorrent clien app:

![image](https://user-images.githubusercontent.com/14793055/76802303-2f178200-67b6-11ea-884f-164b33f306df.png)

I did more some tests. Please, try to do download using this .torrent files:

[TorrentsFiles.zip](https://github.com/alanmcgovern/monotorrent/files/4340548/TorrentsFiles.zip)

**Comment by alanmcgovern** [comment] 2020-03-16 22:09
Hi!

I think the issue is not related to MonoTorrent directly. Can you check the  port mobotorrent is actually listening on, as described here ( https://github.com/alanmcgovern/monotorrent/issues/258#issuecomment-597867720 )

If if is listening correctly, can you use this telnet technique to verify that the 'seeder' really is able to accept connections ( https://github.com/alanmcgovern/monotorrent/issues/258#issuecomment-597904824 ). 

I suspect the issue is that MonoTorrent is not listening on the correct port as the errors you were showing originally showed that a connection could not be established. A connection which is established and then fails handshaking would look different.

**Comment by carlosib** [comment] 2020-03-16 22:12
Hi!
Can you send your email?

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by alanmcgovern** [comment] 2020-03-20 20:27
I'm going to close this thread now as we found the two root causes of the issues you were seeing:

1) The port MonoTorrent was listening on was not accessible because it wasn't forwarded through your firewall/router. The alpha build I sent which uses Mono.Nat to automatically forward ports on UPNP/NAT-PMP routers solved that, or maybe you manually opened the ports and that solved it! Either way we solved it!

2) You were setting TorrentSettings.UploadSlots to 0 to mean 'unlimited'. This was a bug and was fixed with https://github.com/alanmcgovern/monotorrent/commit/ef171db11a542050bf4c85df85697071605b3779. You worked around it by setting UploadSlots to 50 instead.

Thanks for working through this with me!

**Closed by alanmcgovern** 2020-03-20 20:27 UTC
