### ISSUE TITLE
MagnetLink not working

### ISSUE THREAD

**Issue by sekkit** [alanmcgovern/monotorrent#637] opened 2023-02-23 03:29 UTC
Unable to download magnet's metadata, it throws socket address port:6771 can only be used once.
Torrent download works ok.
If using libtorrent then it successfully retrieved metadata.

**Comment by sekkit** [comment] 2023-02-23 04:24
Dual netcard system installed Windows 10

**Comment by jingliancui** [comment] 2023-09-02 01:52
Same issue, are any workaround? Thanks

**Comment by alanmcgovern** [comment] 2024-07-28 22:29
Not really sure what the issue is based on that description. I'll need more information :) I'll close this for now, but if it's reproducible do let me know.

MagnetLink support has been partially rewritten to support BitTorrent V2, so it's possible the issue is fixed in the latest beta release too.

**Closed by alanmcgovern** 2024-07-28 22:29 UTC
