### ISSUE TITLE
Mode=Metadata will not generate any FastResume files？

### ISSUE THREAD

**Issue by BoyFaceGirl** [alanmcgovern/monotorrent#561] opened 2022-10-24 07:50 UTC
If you download from the Magnet URI, the FastResume file will not be generated when the mode=metadata status is set. If you close the download process at this time and reopen it to start downloading, the Magnet URI added previously cannot be found, possibly because the history cache information cannot be found. I tested that many Magnet URI are always in metadata status, and the historical Magnet URI cannot be automatically loaded every time the project is restarted.

**Comment by alanmcgovern** [comment] 2022-10-24 18:15
Ah, interesting.

So what you're saying is that if a `MagnetLink` is added to the engine, then if you save/restore the engine state that magnet link is lost? I'll take a look at this scenario and see what's going on!

**Comment by BoyFaceGirl** [comment] 2022-10-25 02:18
> Ah, interesting.
> 
> So what you're saying is that if a `MagnetLink` is added to the engine, then if you save/restore the engine state that magnet link is lost? I'll take a look at this scenario and see what's going on!

Yes, that is, if adding MagnetLink has not started to obtain torrent and other information, mode=metadata, there is no place to record the magnetic force, and the MagnetLink cannot be loaded when restoring

**Comment by alanmcgovern** [comment] 2022-10-25 23:15
Hrm, that makes sense. I'll try this out again tomorrow to see if i can repro it! It's something i thought was supported and had tests, but i must be missing something!

Thanks for the extra info!

**Comment by BoyFaceGirl** [comment] 2022-10-26 07:21
> > > Ah, interesting.
> > > So what you're saying is that if a `MagnetLink` is added to the engine, then if you save/restore the engine state that magnet link is lost? I'll take a look at this scenario and see what's going on!
> > 
> > 
> > Yes, that is, if adding MagnetLink has not started to obtain torrent and other information, mode=metadata, there is no place to record the magnetic force, and the MagnetLink cannot be loaded when restoring
> 
> My solution is wait for metadata then copy that torrent file in to torrents path
> 
> ```
>         await manager.StartAsync();
> 
>         if (isMetadataMode)
>         {
>             copyTorrentFile(manager);
>         }
> 
>         void copyTorrentFile(TorrentManager manager)
>         {
>               try
>               {
>                   await manager.WaitForMetadataAsync();
>                   File.Copy(manager.MetadataPath, Path.Combine(TorrentsPath, $"{manager.InfoHash.ToHex()}.torrent"));
>               }
>               catch (Exception)
>               {
>               }
>         }
> ```

@uponatime2019  

No. if mode=metadata, **`$"{manager.InfoHash.ToHex()}.torrent")==null `**  it means that the MagnetLink is looking for torrent files in DHT, and torrent has not been found yet. The only effective way is to save the MagnetLink every time you add it, and it can be loaded normally when you restore  it again

**Comment by alanmcgovern** [comment] 2022-10-26 23:16
@BoyFaceGirl I don't think i've understood the issue fully. This is the sample I created to try and match what you described.

https://gist.github.com/alanmcgovern/0084b26be60e8a7beb7b99993c113aee#file-test-cs-L79-L84

in this sample, the TorrentManager is correctly restored when the new engine is created.

Also, the code which restores the state runs this line when re-loading a 'magnet link' based torrentmanager: https://github.com/alanmcgovern/monotorrent/blob/master/src/MonoTorrent.Client/MonoTorrent.Client/ClientEngine.cs#L101 . In turn, this invokes this code https://github.com/alanmcgovern/monotorrent/blob/00992f25fc7c4a966bc2fecaf4f058675f359504/src/MonoTorrent.Client/MonoTorrent.Client/ClientEngine.cs#L394-L397 which ensures that if the torrent file had been downloaded before, then it *will* be loaded ~immediately (i.e. it won't have to search DHT for peers and re-download the torrent file).

**Comment by alanmcgovern** [comment] 2022-10-26 23:21
> If you download from the Magnet URI, the FastResume file will not be generated when the mode=metadata status is set

If you're referring to actual `FastResume` files, then you're correct. These will not be created in metadata mode. FastResume file can only be created *after* the torrent metadata has been downloaded from DHT and the torrent is Downloading or Seeding ( https://github.com/alanmcgovern/monotorrent/blob/f54c4ead433ac7ef7541636bd7f884e9930201ad/src/MonoTorrent.Client/MonoTorrent.Client.Modes/DownloadMode.cs#L87-L90 ) .

FastResume files only store information about which pieces have been successfully downloaded. If the metadata hasn't been downloaded yet, then no pieces could be successfully downloaded, so there's no need to create a fast resume file which says that.

**Comment by BoyFaceGirl** [comment] 2022-10-27 08:01
> > If you download from the Magnet URI, the FastResume file will not be generated when the mode=metadata status is set
> 
> If you're referring to actual files, then you're correct. These will not be created in metadata mode. FastResume file can only be created _after_ the torrent metadata has been downloaded from DHT and the torrent is Downloading or Seeding ( `FastResume`
> 
> https://github.com/alanmcgovern/monotorrent/blob/f54c4ead433ac7ef7541636bd7f884e9930201ad/src/MonoTorrent.Client/MonoTorrent.Client.Modes/DownloadMode.cs#L87-L90
> 
> ) .
> FastResume files only store information about [which pieces have been successfully downloaded](https://github.com/alanmcgovern/monotorrent/blob/f54c4ead433ac7ef7541636bd7f884e9930201ad/src/MonoTorrent.Client/MonoTorrent.Client/FastResume/FastResume.cs#L51-L55). If the metadata hasn't been downloaded yet, then no pieces could be successfully downloaded, so there's no need to create a fast resume file which says that.

Would you consider solving this problem? Record the Magnet Urlthat did not start downloading to ensure that the Magnet Url force can be loaded correctly when downloading again?

**Comment by alanmcgovern** [comment] 2022-10-27 12:54
I think I don't understand the issue yet. 

The fact there is no fast resume data stored for TorrentManagers which have not downloaded any data is not a bug. Having no fast resume data is the same as having fast resume data which has all pieces marked as "Not Downloaded Yet".

As I think about this some more, are you saying the issue is more like this:
1. Add a magnet link to the engine and start it. The torrent enters metadata mode.
2. peers are discovered via DHT and the metadata is downloaded. 
4. The torrent enters downloading mode. 
5. The engine state is saved, the program is restarted, and you restore the old engine state. 
6. A torrent manager is recreated using the same magnet link. The progress is reported as 0% complete because either no fast resume data was stored as part of step 4, or it wasn't reloaded as part of restoring the TorrentManager. 

If that's what's occurijg I can review step 4 and 6 to ensure fast resume is created/used for these scenarios :)

If I have described it incorrectly, please let me know!

**Comment by BoyFaceGirl** [comment] 2022-10-28 01:00
> I think I don't understand the issue yet.
> 
> The fact there is no fast resume data stored for TorrentManagers which have not downloaded any data is not a bug. Having no fast resume data is the same as having fast resume data which has all pieces marked as "Not Downloaded Yet".
> 
> As I think about this some more, are you saying the issue is more like this:
> 
> 1. Add a magnet link to the engine and start it. The torrent enters metadata mode.
> 2. peers are discovered via DHT and the metadata is downloaded.
> 3. The torrent enters downloading mode.
> 4. The engine state is saved, the program is restarted, and you restore the old engine state.
> 5. A torrent manager is recreated using the same magnet link. The progress is reported as 0% complete because either no fast resume data was stored as part of step 4, or it wasn't reloaded as part of restoring the TorrentManager.
> 
> If that's what's occurijg I can review step 4 and 6 to ensure fast resume is created/used for these scenarios :)
> 
> If I have described it incorrectly, please let me know!

ok，you ara right。

**Comment by alanmcgovern** [comment] 2022-11-03 22:53
@BoyFaceGirl I've double checked how fast resume is saved/restored when torrents are fetched using a `MagnetLink` and everything looks ok. It sounds like you agree that the current behaviour is OK, so if you have any further issues do let me know!

Other than that, I have one piece of good news! The short version is: magnet link downloads should be much faster and more reliable. Every block of data is now requested multiple times concurrently (as was originally intended) :) 

The bug was in this line of code, and the detailed explanation is  this:

https://github.com/alanmcgovern/monotorrent/blob/90e89d540c1909a5ff96ca5a7bb4da96e38b25a3/src/MonoTorrent.PiecePicking/MonoTorrent.PiecePicking/StandardPieceRequester.cs#L143-L156

In short - when the engine was downloading torrent metadata, the `available` bitfield linked above would have all it's bits set to 'false'. To ensure the piecepicker would still be able to request blocks of data, the engine would create a fake bitfield where all bits were set to true  ( `filtered ??= ApplyIgnorables (Temp!.SetAll (true));` ). However, the check to see if 'end game mode' should be used incorrectly used `available.AllTrue` instead of the `filtered.AllTrue`  ( `else if ((InEndgameMode || available.AllTrue)` ). This meant that endgame mode would never be activated while in `MetadataMode`. Whoops!

The net effect was that instead of sending multiple requests for each block of data in the 'metadata', only a single request would be sent, and if the peer didn't fulfil that request then there could be a long timeout until a new request was sent.

This has now been fixed by removing these workarounds  and implementing a cleaner solution which solves this problem for both `MetadataMode ` (used to fetch the .torrent data when using a magnet link) and `PieceHashesMode` (used to download the piece hashes for bittorrent v2 torrents). https://github.com/alanmcgovern/monotorrent/commit/70a00ac28b48f8235e8247b1d5fb45c5fe410c3f

This should make slow metadata downloads much less of a problem :)  

I'll close this ticket for now, but please do let me know if you have issues with slow metadata fetching with the next release. I'll push one to nuget.org in a few minutes :)

**Closed by alanmcgovern** 2022-11-03 22:53 UTC

**Comment by alanmcgovern** [comment] 2022-11-04 00:42
I found one or two more issues worth fixing (see issue #559 ) so I'll release an update with the fixes for this issue, and the fixes for #559, on Sunday.
