### ISSUE TITLE
Starting, Stopping, and Hashing operations are blocking MainLoop

### ISSUE THREAD

**Issue by vlasenkoalexey** [alanmcgovern/monotorrent#223] opened 2020-01-25 20:52 UTC
Whenever one of the torrent managers are in Starting, Stopping, and Hashing state, others can't do any work.

From my experience if one of the torrents is in blocking state, system won't respond to adding new torrents, and existing torrents won't be able to change state until blocking operation completes.

As far as I understand current implementation, async/await operations are queued to MainLoop instead of ThreadPool as usual. So any long-running op, can block whole program.  Therefore those operations should be executed off MainLoop.

**Comment by alanmcgovern** [comment] 2020-01-26 00:29
Hrm, that doesn't make a whole lot of sense to me based off what I remember the code doing. StoppingMode should be completely asynchronous and doesnt have operations which block the thread it's executing on. 

Do you have any further details about what exactly is blocking? Perhaps there's some unintended/unforseen synchronous blocking in some network code which is supposed to be asynchronous? I believe some networking APIs resolve DNS synchronously even if you're using async methods and can cause issues like you describe.

**Comment by alanmcgovern** [comment] 2020-01-29 05:45
@vlasenkoalexey If you have any further information do let me know, otherwise I'll go ahead and close this issue as the current implementation is non-blocking and does allow one torrent to be started while a second one is stopping.

**Comment by vlasenkoalexey** [comment] 2020-01-30 05:55
I'll try to get a repro using profiler, or just extend sample app by adding relevant log information.
I clearly observe that behavior in my app, but I had to do a lot of changes to monotorrent library in order to make it work for UWP. But given my current understanding of how things work I believe that issue exists in core library.

**Comment by alanmcgovern** [comment] 2020-02-01 04:32
Perfect, thank you!

I suspect the problem will most likely be related to an asynchronous networking API which is not actually asynchronous. I should do a double check of the docs around socket/webrequest and see where DNS queries may cause the behaviour you describe.

**Comment by alanmcgovern** [comment] 2020-02-02 02:20
I added some new API to ensure that you can load `.torrent` files without blocking the thread.

https://github.com/alanmcgovern/monotorrent/commit/7a9e01b9cd06eeaa51bb7604f20e689bf1ec417b

I have not found anything which would block the main loop for more than 300ms or so. However, i have made some changes for some minor sources of mainloop blocking. Do let me know how your investigations go.

**Comment by alanmcgovern** [comment] 2020-02-08 00:46
I'll go ahead and close this for now. If you are still having issues with the latest release do let me know. The latest stable release has some modifications to explicitly move async tasks to threadpool before starting the operation. This should ensure that the library is protected from any hidden synchronous calls. 

Thanks for reporting, and hopefully my guess was correct!

**Comment by vlasenkoalexey** [comment] 2020-02-24 03:46
I finally got time to do more debugging, and I found that app is locking on 
await ClientEngine.MainLoop;

Repro is simple if you have a dummy app you can call MonoTorrent from.
Add a stopwatch to measure how much time it takes to execute await ClientEngine.MainLoop;, for example:

```
        public async Task StopAsync (TimeSpan timeout)
        {
            var watch = System.Diagnostics.Stopwatch.StartNew ();
            // the code that you want to measure comes here
            await ClientEngine.MainLoop;

            watch.Stop ();
            Debug.WriteLine ("ClientEngine.MainLoop took {0} ms", watch.ElapsedMilliseconds);

            if (Mode is StoppingMode)
```
Add two or more torrents that have multiple files, it takes a while for Hash, Start, and Stop them.
Start downloading, wait for MonoTorrent to start writing data to disk, and then call TorrentManager.StopAsync for all files, and observe results.

As far as I understand  await ClientEngine.MainLoop waits until all tasks previously queued are executed. Usually tasks are small, like network operations, and this is not a problem.
But there are few which might take more than few seconds: WaitForStoppingToComplete, WaitForHashingToComplete. And since MainLoop is shared between TorrentManagers, await ClientEngine.MainLoop would also block others.

I might have misunderstood some details, but from what I observe, look like this is the case.
Such behavior might be fine for library, but for an App, it is a terrible experience when user has to wait for Hashing to complete for example, before any other downloads could be able to change state.

Btw, removing await ClientEngine.MainLoop; from StartAsync, StopAsync, etc in TorrentManager makes it look more responsive. Will use it for few days, to see if there are some side effects. 
And this wasn't an issue in pre async version of MonoTorrent.

Unfortunately I'm not sure what is the right way to fix this, and what is the logic behind putting await ClientEngine.MainLoop in the code. Probably it should be safe to remove it in most of places, and where it is needed for specific reasons, use other synchronization mechanisms.

**Comment by vlasenkoalexey** [comment] 2020-02-24 03:49
@alanmcgovern , looks like I don't have permissions to reopen this issue, please let me know what do you think.
Thanks!!!

**Comment by alanmcgovern** [comment] 2020-02-24 09:56
I just reopened the issue. 

Removing the calls to sync to the main thread is likely to be problematic. It definitely introduces race conditions which will make arbitrary things fail. 

Before the async/await rewrite the main loop was maintained with a simpler "lock". The old mechanism wouldn't have had any real difference in behaviour I'm the circumstances you're describing, except things would've more visibly hung. 

I have enough information to get going, though I have one last request if you have the time. 

When you're waiting for your task to run on the main thread could you hit "pause" in the debugger and see where the main loop is? I'm curious as to which piece of code is executing. 

If you can't - don't worry about it. I can probably pick this out using a profiler in a few seconds. I just wanted independent verification to be 100% sure I resolve your issue.

**Comment by alanmcgovern** [comment] 2020-02-24 22:58
@vlasenkoalexey Using tip of master, is there a noticeable difference in performance when you attach to the `TorrentManager.PieceHashed` event as compared to when you do not attach to that event? I wouldn't anticipate it making much of a difference as you'd have to be hashing 500,000+ pieces before it begins to take a human-noticeable amount of time (according to the profiler), and even still I would expect an `await MainLoop` call to interleave itself in a way which results in the call executing within a reasonable amount of time.

While a torrent is in the steady state of downloading, most of the threads are idle 99% of the time:
![while_downloading](https://user-images.githubusercontent.com/264396/75198592-ec373100-5758-11ea-9601-bac50b1d97ee.png)

I've profiled the hashing/starting case multiple times now and on my machine there is precious little left to optimise. There was one issue where torrents with a lot of files would consume an unnecessarily high amount of CPU, however that shouldn't really cause noticeable delays to humans, it should just making hashing slower. https://github.com/alanmcgovern/monotorrent/pull/252 did address that issue though.

**Comment by alanmcgovern** [comment] 2020-02-24 23:23
Here's a performance trace of a 2.3GB torrent being hashed 10 times in a row.

![hashing_23gb](https://user-images.githubusercontent.com/264396/75199898-3c63c280-575c-11ea-8f8f-972477cc5fa5.png) . There's 22.7 seconds of disk access time and 50 seconds of sha hashing all on the Disk IO thread. This covered 23GB of data in a single-file torrent.

There's 30ms on the main 'Client Engine' loop.

I am very curious about anything which causes slowdowns on the 'Client Engine' loop, which is the most important one for user interactivity.

**Comment by alanmcgovern** [comment] 2020-02-24 23:35
> then call TorrentManager.StopAsync for all files, and observe results.

Actually I wonder if this can be answered as 'By Design'. The XML documentation for this method, which should show up in your IDE, states:

```
        /// <summary>
        /// Stops the TorrentManager. The returned task completes as soon as the manager has fully stopped. The final
        /// tracker announce will be limited to the maximum of either 2 seconds or <paramref name="timeout"/> seconds.
        /// </summary>
```
Firstly, I think that comment is incorrectly describing what happens. The *minimum* time it will wait for the final tracker announce is 2 seconds even if a timeout shorter than 2 seconds is passed in.

If you pass in a timeout of 10 seconds, then it will wait approximately 10 seconds before giving up.

However the essence of the text is accurate - the returned task will not be marked as complete until after the final tracker announce completes. You need to keep this in mind when awaiting the task. You may want to run some additional logic before awaiting it, or you may want to await it in an `async void` method so the rest of your application doesn't wait for the torrent to complete all of the tracker announces.

For example:

```
async Task StopTheTorrentManager (TorrentManager manager)
{
    var task = manager.StopAsync ();
    // Wait for this task to complete asynchronously, in a way that doesn't delay execution
    // of other methods.
    WaitForCompletion (manager, task);

    // This will execute before the stopping task to complete.
    CacheSomeData (manager);
    // This is a bad example as the UI is probably wired to the 'StateChanged event
    // however this is one way to set the torrent manager's state to 'Stopping' immediately.
    SetStateInUIToStopping (manager);
}

async void WaitForCompletion (TorrentManager manager, Task stoppingTask)
{
    await stoppingTask;
    SaveFastResumeData (manager);
    // Now that the manager has completely stopped we can set it's state to 'Stopped'
    // NOTE: This is a bad way of doing things, but it's just an example :)
    SetStateInUIToStopped (manage);
}
```

**Comment by vlasenkoalexey** [comment] 2020-02-25 08:25
Thanks for looking into this and for detailed analysis.
I think I looked at thread during time when application was starting/stopping, but probably missed the point.
Now I see that at least during starting client engine loop thread is on the following line most of the time:
        async Task<UdpTrackerMessage> SendAndReceiveAsync (UdpTrackerMessage msg)
        {
            var cts = new CancellationTokenSource (TimeSpan.FromSeconds (RetryDelay.TotalSeconds * MaxRetries));

            try {
                using (var udpClient = new UdpClient (Uri.Host, Uri.Port))

As far as I understand that is a blocking operation, and it shouldn't be a problem to change it to async. I'll give it a shot.
Thanks for the pointer!!!

**Comment by alanmcgovern** [comment] 2020-02-25 08:49
Oh weird. I would definitely not have expected creating a UdpClient object to be slow. If that's where the time is being spent then perhaps calling "await MainLoop.SwitchToThreadpool()" before that line will solve it safely. I'd need to check what the threading concerns are for the rest of the method, and other invoked methods. If they need to be on the main client engine loop then we can always switch back when the expensive work is done!

Good detective work tracking that down as it wasn't happening on my machine!

**Comment by alanmcgovern** [comment] 2020-02-25 08:52
If this is the equivalent code in master then adding the threadpool switch looks safe! The version you have looks a bit older :)

https://github.com/alanmcgovern/monotorrent/blob/aa7a282d6d41c4b34fc86f2098ae32eceef51abb/src/MonoTorrent/MonoTorrent.Client.Tracker/UdpTracker.cs#L126

**Closed** 2020-02-26 18:57 UTC

**Comment by alanmcgovern** [comment] 2020-02-26 19:04
I'm pretty sure this cause for your issue has been resolved.

![sync_dns](https://user-images.githubusercontent.com/264396/75377764-63400700-58ca-11ea-9de8-7b3f52c647d6.png)

Like I suggested before ( https://github.com/alanmcgovern/monotorrent/issues/223#issuecomment-578456775 ) sometimes .NET likes to hide synchronous network requests in unexpected places. If you instantiate a UdpClient by passing it a hostname, or if you call Connect with a hostname, you will do a synchronous DNS lookup for the underlying IP address.

In my case it took 125ms to look up some fake hostnames. I've seen it take much longer. The fix I just pushed ensures that this lookup is guaranteed to occur on a ThreadPool thread so it won't impact the engine in any way.

I took a look around and that looks like the only piece of code which instantiates UdpClients with hostnames so this could be the only source of this particular issue. Please let me know how you get on with this change!

**Comment by alanmcgovern** [comment] 2020-02-26 19:06
I'm pretty sure this cause for your issue has been resolved.

![Uploading sync_dns.png…]()


Like I suggested before ( https://github.com/alanmcgovern/monotorrent/issues/223#issuecomment-578456775 ) sometimes .NET likes to hide synchronous network requests in unexpected places. If you instantiate a UdpClient by passing it a hostname, or if you call Connect with a hostname, you will do a synchronous DNS lookup for the underlying IP address.

In my case it took 125ms to look up some fake hostnames. I've seen it take much longer. The fix I just pushed ensures that this lookup is guaranteed to occur on a ThreadPool thread so it won't impact the engine in any way.

I took a look around and that looks like the only piece of code which instantiates UdpClients with hostnames so this could be the only source of this particular issue. Please let me know how you get on with this change!

**Comment by alanmcgovern** [comment] 2020-02-26 19:08
Also - thanks for taking the time to double check what was blocking the engine for me! Without you pointing at that UdpClient line I probably would not have discovered this :)
