### ISSUE TITLE
Mono.Nat null reference exception

### ISSUE THREAD

**Issue by razaqq** [alanmcgovern/monotorrent#507] opened 2022-01-22 13:33 UTC
Im using latest monotorrent (`2.0.4`) with `AllowPortForwarding = true` for engine settings hoping to get automatic port forwarding

im pretty often getting this exception:
object null `at Mono.Nat.SocketGroup.<ReceiveAsync>d__11.MoveNext()` with the object being a dictionary (sorry the stack trace doesnt give much more than that)

It must be referring to this https://github.com/alanmcgovern/Mono.Nat/blob/1674ed233129ff56b8f5b4da6820962948987b5a/Mono.Nat/SocketGroup.cs#L33

![grafik](https://user-images.githubusercontent.com/5948878/150640249-32f91793-5a06-4e6f-82ce-3bb7d8becb18.png)

im not sure if this issue stems from monotorrent (how it uses mono.nat) or mono.nat itself, but im opening it here first

**Comment by alanmcgovern** [comment] 2022-01-24 22:49
Hrm, i'm not sure what could be triggering that. Does the library still successfully forward ports for you? Is this just a transient issue which the library recovers from?

Either way, would you be able to compile mono.nat from source and see if you can figure out which part is throwing a null reference? There's a sample application which invokes a few UPNP operations on each discovered device, hopefully that will trigger the problem too.

**Comment by alanmcgovern** [comment] 2022-07-09 23:49
I'll close this as i can't reproduce this. Let me know if this a problem with newer releases.

**Closed by alanmcgovern** 2022-07-09 23:49 UTC
