### ISSUE TITLE
MonoTorrent Tracker and MonoTorrent seeding client does not work with WebTorrent client

### ISSUE THREAD

**Issue by karoltrzaskawka** [alanmcgovern/monotorrent#300] opened 2020-05-14 14:46 UTC
Hi,

I am working on sending files between client application written using WebTorrent(https://webtorrent.io/) in combination with MonoTorrent tracker and MonoTorrent client. The issue is that i am not able to download file with WebTorrent, when using MonoTorrent as an initial Seed. When i am seeding file with qBitTorrent app it works fine.

**Assumptions**
- WebTorrent app is located on client device which need to download the files and is written in node.js
- Tracker is written using MonoTorrent library in combination with .NET Core app. 
- Initial seeding client is written using MonoTorrent library in combination with another .NET Core app. It resumes torrent file and work in background during whole applicaiton lifecycle.

**Current behavior**
- WebTorrent client works fine with qBitTorrent as seed(MonoTorrent tracker and .torrent file created with MonoTorrent) and does not work when MonoTorrent stands for seeding files.
- qBitTorrent and other Torrents are able to download file without any issues
- MonoTorrent keeps entering Listener's NewConnection event, each time using new ports in infinity loop after WebTorrent finish download using qBitTorrent app as seed.
- When trying to download files using MonoTorrent as seed i am getting PeerAnnounced event trigered, which says that Peer has 0 of total_number_of_parts downloaded and nothing more is happening both on MonoTorrent client and WebTorrent client. Every retry of download using MonoTorrent as Seed result in the same result.

**Sample code of MonoTorrent seeding client**

```
	public async Task RegisterSeedAndRun(Stream torrentContent)
        {
            var mt = MonoTorrent.Torrent.Load(torrentContent);
            BitField bitfield = new BitField(mt.Pieces.Count);
            FastResume fastResumeData = new FastResume(mt.InfoHash, bitfield.Not());

            MonoTorrent.Client.TorrentManager mr = new TorrentManager(mt, _localFileRepositoryOptions.Value.UploadedFileSavePath);
            mr.Settings.AllowInitialSeeding = true;
            mr.ConnectionAttemptFailed += ConnectionAttemptFailed;
            mr.LoadFastResume(fastResumeData);

            await _engine.Register(mr);
            _managers.Add(mr);
            await mr.StartAsync();
        }
```

**Sample code of Tracker**

```
	public TrackerManager(ILogger logger,
			IOptions<TrackerServerOptions> serverOptions)
		{
			_serverOptions = serverOptions;
			_server = new TrackerServer(_serverOptions.Value.TrackerId.ToString());
			StartServer(serverOptions.Value);
			_logger = logger;
		}
	private void StartServer(TrackerServerOptions options)
		{
			var endpointAddress = $"{options.Prefix}://{options.Hostname}:{options.Port}/torrent/announce/";
			var listener = TrackerListenerFactory.CreateHttp(endpointAddress);
			_server.PeerAnnounced += PeerAnnounced;
			_server.PeerTimedOut += PeerTimedOut;
			_server.RegisterListener(listener);
			
			listener.Start();
			_server.AllowUnregisteredTorrents = options.Public;
		}
	public void RegisterTrackable(Stream torrentContent)
		{
			var torrent = MTorrent.Load(torrentContent);
			InfoHashTrackable trackable = new InfoHashTrackable(torrent);
			_server.Add(trackable);
		}
```

**Comment by alanmcgovern** [comment] 2020-05-17 19:54
Your code looks fine at first glance.

I've never used WebTorrent before so I'll download it and give it a quick test. I'm curious!

**Comment by alanmcgovern** [comment] 2020-05-17 21:07
I just made a torrent, seeded it in MonoTorrent and then used WebTorrent to stream/play it.

It worked just fine for me. For a while I thought it was buggy as WebTorrent had connected but wasn't transferring data, but then I realised i had to *play* the media file before WebTorrent would begin transferring any data.

Can i just double check you're using MonoTorrent 1.0.21, the current release?

**Comment by karoltrzaskawka** [comment] 2020-05-18 11:49
Thank You for quick response. I'v been using 1.0.20 version before. I did update the version today morning, but the problem still exists. I'v also tried official desktop version of WebTorrent which is already as an .exe file and i have found something weird.  When i rerun download only for the single file which is inside torrent(not whole torrent) it sometimes starts the download immediately but with low speed equal to 66KB/s. Unfortunatelly it does not work every time and it completely does not work when i am using WebTorrent library with node.js. When seeding with uTorrent it works good and speed is also high. Maybe it is WebTorrent's fault or it's implementation because when we add peer(Mono torrent seed) in WebTorrent(node.js) manualy, it always says that it is not interrested in connection to that peer. However when we manually add another WebTorrent App written using node.js as a Peer it works every single time. We have opened Issue on WebTorrent GitHub aswell, which is all about adding peers manually, which does not work with every torrent client as a peer and we are waiting for their response.

**Comment by alanmcgovern** [comment] 2020-05-18 19:07
I did find webtorrents behaviour unusual. It sent interested messages only when a file was being played. This is ok, but odd. Why establish connections and not use them?

However it did send Unchoke messages in a buggy way. I was a seeder so i should never be sent an Unchoke message. 

I didn't diagnoss any further than that as it did start streaming

**Comment by alanmcgovern** [comment] 2020-05-25 23:42
@karoltrzaskawka  It looks like this is a confirmed bug in WebTorrent [0] so I'll go ahead and close this. It's not surprising that the bug was in how InterestedMessages were being sent. I did notice they were not being sent like a normal client would :)

https://github.com/webtorrent/webtorrent/issues/1864

**Closed** 2020-05-25 23:42 UTC
