### ISSUE TITLE
UWP app crash when almost finish downloading

### ISSUE THREAD

**Issue by uponatime2019** [alanmcgovern/monotorrent#431] opened 2021-04-04 06:40 UTC
Hello,

I've made an UWP for downloading torrent. I still using monotorrent 1.0.24 since last year. I can't made an package update because too many API changes and I made some source code edit to adaptive my app needed

Many users report that app crash when torrent almost finish like 80~90%, usually at some big files. I'm tested but problem never happen when debugging with Visual Studio

Did new API have a fix related to that? Thanks in advance

**Comment by alanmcgovern** [comment] 2021-04-04 10:37
I don't really know. It's definitely possible that something has been fixed. It may also be possible  that your changes caused the issues. If that's the case then updating wouldn't help.

I think the best path forward here would be for me to understand exactly what is needed to support UWP.

I have a WIP branch to support UWP better, but I never really knew what your issues were. If you're interested in upstreaming changes bit by bit, we could ensure the 2.0 release has a way of doing all the things you need it to when running in a uwp context.

**Comment by uponatime2019** [comment] 2021-04-04 12:52
Yep thank you. I'm rebuilding an UWP app from scratch with version 2.0. Thanks for continuing support this awesome project

**Comment by alanmcgovern** [comment] 2021-04-18 11:13
I'll close this issue for now as it's not possible to tell what the issue is at the moment. Hopefully if you can port to an unmodified 'monotorrent 2.0' then the issue will go away :)

**Closed by alanmcgovern** 2021-04-18 11:13 UTC
